server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

spring:
  data:
    web:
      pageable:
        default-page-size: 5
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  application:
    name: services
  datasource:
    username: 'postgres'
    url: jdbc:postgresql://localhost:5432/company_management_services
    password: 'TecPsql'
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    show-sql: 'false'
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false